# Generated by Django 2.2.4 on 2019-08-11 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='cashOnHand',
        ),
    ]
